### ISSUE TITLE
[FEATURE] Block authorization when Docker inspection fails

### ISSUE THREAD

**Issue by ElioDiNino** [steveiliop56/tinyauth#393]
**Is your feature request related to a problem? Please describe.**
I use a socket proxy with Tinyauth for security reasons which I am glad to see Tinyauth explicitly calls out and supports. However, the [label-based access control configurations](https://tinyauth.app/docs/guides/access-controls/) means that if the socket proxy ever goes down or blocks a given request, these labels are not read by Tinyauth. I can see the current logic ([ref](https://github.com/steveiliop56/tinyauth/blob/cbe31d442db2995a1a065cfc6ec9445d6ad9c53c/internal/service/docker_service.go#L71-L98)) prints a warning and ignores any Docker socket issues it runs into, but this allows for users to be authorized to services they otherwise wouldn't be able to if a label specified user or role-based gating.

**Describe the solution you'd like**
My ask is that a new configuration option be added that lets users choose whether Tinyauth continues authorization when labels can't be read (i.e. the current logic) or shows an error to the user saying something like "Sorry, an error has occurred. Please contact an administrator." to prevent any authorization while the Docker socket is returning errors. Something like `REQUIRE_DOCKER_SOCKET` seems reasonable to me.

**Describe alternatives you've considered**
Another solution would be to switch to my desired behaviour as the default, but this would technically be a breaking change and I think having this configurable is better for everyone.

**Additional context**
I discovered this issue after setting up Tinyauth and playing around with the access controls. When they weren't working (anyone could authorize, not just the oauth group I specified with `tinyauth.oauth.groups`) I saw that my socket proxy was blocking requests due to some regex needing updating. This made me think about similar cases and the bad security implications of the proxy crashing or denying requests with the current application logic.

Tinyauth Logs
```
2025-10-08T02:08:08.476804146Z 2025-10-08T02:08:08Z INF Request address=172.21.0.6:33064 latency=81.241961ms method=GET path=/api/auth/caddy status=200
2025-10-08T02:08:09.307604880Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=9ef86406cf75ed676bb2f3e3662dc354bcf37f697fa8e646182655b6c19b90b7
2025-10-08T02:08:09.311381094Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=9d16d63974c32cc452a3b600ed90353c3b05e3ccb58aba5e9e28ea411bb3360d
2025-10-08T02:08:09.314890046Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=1109708d3d906e01abd0f860e34b9efccdec47c69d6e921a1d041a7df3694bc0
2025-10-08T02:08:09.318873395Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=577253f534953af7893c7ce51c7094738837c472ac855352370b6654e6ad9f4f
2025-10-08T02:08:09.323017834Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=addb7b298c4174a03ca3163a464970f90bfcafbe28b30d7e1ad7d5f620f667ef
2025-10-08T02:08:09.327004641Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=4f5be201b61abaf4cd108874cb780306ed9d5c7f7abbba30b76653219069317a
2025-10-08T02:08:09.331060326Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=f6c52f379989d8f153668aeaf44179a321c2a9c97191372fbbebdf8f64b4b3b1
2025-10-08T02:08:09.334863167Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=9c8a935674d13a212bbf4575f813e674ff71fef2833394455f7b15cbe1324c6b
2025-10-08T02:08:09.338712884Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=592feab079576a8399425b87f17db435fcfb5eac84e86b0134c3600b306db038
2025-10-08T02:08:09.342899200Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=343d5a18cb11d3ef5524eeea8f72ff797f9510f8651c0e7c094d365cb82efd1a
2025-10-08T02:08:09.346939260Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=0e7e8824e045c116fabba21f346cfd825e9a163f1808556e8140cbe6c4f0667f
2025-10-08T02:08:09.350410960Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=c23350b07eca1d748da6c19ecb7be5980ff3b6396f616f68462c26d34061599b
2025-10-08T02:08:09.354260761Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=c15889da8dd8d399a23f5a75e11df9ebeb1832f97f734e2641ad53f8b2c76e6f
2025-10-08T02:08:09.357929220Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=25e09f9c50e6364c6734d42027d7a871416eca3e237855aae9df37b269884394
2025-10-08T02:08:09.361848191Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=fa62762dff21be311826e3e83fb2e17d5633be4930b12666d60a72baf44ba7db
2025-10-08T02:08:09.365678116Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=38d8709db6de23b5d36e9db63a21cf33e8c9ff355cead48ba2092f89a80bef94
2025-10-08T02:08:09.369216027Z 2025-10-08T02:08:09Z WRN Error inspecting container, skipping error="Error response from daemon: Forbidden" id=647caa04c5b0d887ca7513b70372d78c98d81f7f536322b615e07dd00aedfcae
```

**Comment by steveiliop56** [comment]
Fixed in https://github.com/steveiliop56/tinyauth/commit/287c6f975fbc4044de10ac2ac21ba6756a61b49f. Thank you for letting me know!

**Comment by ElioDiNino** [comment]
> Fixed in [287c6f9](https://github.com/steveiliop56/tinyauth/commit/287c6f975fbc4044de10ac2ac21ba6756a61b49f). Thank you for letting me know!

Thanks for the quick reply and implementation! While this fixes a big part of the issue (if a Docker socket request gets blocked), it does not solve the case where the socket proxy crashes or is unavailable for any reason (i.e. the ping fails) since [the logic](https://github.com/steveiliop56/tinyauth/blob/main/internal/service/docker_service.go#L61-L64) skips at that point. The tricky part is that this configuration makes sense for any users not configuring Tinyauth with Docker labels (they don't mount the Docker socket or a socket proxy), so I think a config value still may be needed.

**Comment by steveiliop56** [comment]
It covers the case where the socket proxy crashes. If it crashes, Tinyauth won't be able to get the containers and thus it won't allow access. As for non-docker ACLs, it's something that I might consider in the future.

**Comment by ElioDiNino** [comment]
> It covers the case where the socket proxy crashes. If it crashes, Tinyauth won't be able to get the containers and thus it won't allow access.

Maybe I am misunderstanding the code, but the following snippet runs first before container fetching:

https://github.com/steveiliop56/tinyauth/blob/ae8347fd28fec6c6fac285f0278eebca6a7c16ed/internal/service/docker_service.go#L59-L64

This to me looks like if the Docker socket is not connected (i.e. either it is not mounted, it crashed, or is unavailable for any reason), then it skips any label fetching, returning to the issue at hand.

> As for non-docker ACLs, it's something that I might consider in the future.

That would be cool

**Comment by steveiliop56** [comment]
Ohh I get what you mean. I will just move the ping to start up.

**Comment by ElioDiNino** [comment]
> Ohh I get what you mean. I will just move the ping to start up.

Ah yeah that also works, thanks!

**Comment by steveiliop56** [comment]
Fixed for good in https://github.com/steveiliop56/tinyauth/commit/5a4855c12c05ef884a40e4a32f139cf27fa3f1b5. The docker service will initialize the client, try to ping the daemon and if it fails it deinitializes everything and returns empty labels every time.
